<a href="https://colab.research.google.com/github/2303A51867/2303A51867/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

#ARRAY
import numpy as np
thislist = np.array(["apple", "banana", "cherry"])
print(thislist)
array = np.array([1, 2, 3, 4, 5])
print(array)
# Access elements
print(array[0])
print(array[1:4])
# Append to array
array = np.append(array, 6)
print(array)
#insert elements
array = np.insert(array, 2, 99)
print(array)
#delete elements
array = np.delete(array, 2)
print(array)
#array type
print(" Array:",array)
print("Type of np_array:", type(array))
#array multiplication
np_array1 = np.array([1, 2, 3, 4, 5])
np_array2 = np.array([2, 2, 2, 2, 2])
np_multiplication = np_array1 * np_array2
print("Array Multiplication:", np_multiplication)
#array division
np_division = np_array1 / np_array2
print(" Array Division:", np_division)
#array power
np_power = np_array1 ** 2
print(" Array Power:", np_power)
#Combine text with Numpy fuction to generate a textual output - ”Addition of Two array1 +array 2:"
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])
array_sum = array1 + array2
textual_output = f"Addition of Two:\n{array1} + {array2} = {array_sum}"
print(textual_output)



['apple' 'banana' 'cherry']
[1 2 3 4 5]
1
[2 3 4]
[1 2 3 4 5 6]
[ 1  2 99  3  4  5  6]
[1 2 3 4 5 6]
 Array: [1 2 3 4 5 6]
Type of np_array: <class 'numpy.ndarray'>
Array Multiplication: [ 2  4  6  8 10]
 Array Division: [0.5 1.  1.5 2.  2.5]
 Array Power: [ 1  4  9 16 25]
Addition of Two:
[1 2 3 4 5] + [5 4 3 2 1] = [6 6 6 6 6]
